services:
  caddy:
    image: caddy:2.8-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - api

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    expose:
      - "80"

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "3000"

volumes:
  caddy_data:
  caddy_config:
